name: Test-workspace

on: push

jobs:
    first:
        runs-on: ubuntu-latest
        steps: 
        - name: Repo action
          uses: actions/checkout@v4
        - name: testing first time
          run: echo "first github actions step". #echo used based on runs-on OS
          
          
        - name: list files
          run: ls
        
        - name: read file READ.md
          run: cat README.md

